### ISSUE TITLE
Session Data Not Passed to Custom Routes

### ISSUE THREAD

**Issue by zhsolutions** [botble/issues#10]
Maybe I missed something, Maybe not but I created a custom route, to load a custom page, If the visitor to the page was logged in, a message would appear, or if not logged in, a different message.

Long Story short, the session data IS not sent to a custom route.. which I find odd. 

Example I place this Route inside the RouteServiceProvider of core/base (to prove this issue)
        \Route::get('/account', [
            'as' => 'user.page',
            'uses' => 'Botble\Membership\Http\Controllers\ConceptProofController@conceptProved',
        ]);

The function runs  
if(!Sentinel::check()) {
          return 'Not Logged In';
        }
return 'Hi buddy';

No matter what, Not Logged In displays... and in the debugbar I enabled, Nothing is sent in the session EXCEPT the _token

**Comment by sangnguyenplus** [comment]
Do you put your routes to middleware "web"?
Sentinel::check() just work with session. So if you don't pull your route to middleware "web", Sentinel::check() will always return false.

Thanks!

**Comment by zhsolutions** [comment]
Hey

Just before I went to bed, I got it working by wrapping my route into the web middleware.

Thanks

**Comment by sangnguyenplus** [comment]
Good news :)
