### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by ccLaravel** [botble/issues#12]
Hello I have been using the plugin "Custom Field"
My question is, which function should I use to get the values on a page.

**Comment by sangnguyenplus** [comment]
Hi @ccLaravel,
Currently, there four functions can use to get and check the value. You can see it on `plugins/custom-field/helpers/helpers.php.`

```
- get_field.
- has_field.
- get_sub_field.
- has_sub_field.
```

Thanks!
