### ISSUE TITLE
Roles and Permission Error

### ISSUE THREAD

**Issue by zhsolutions** [botble/issues#13]
DataTables warning: table id=dataTableBuilder - Exception Message:
No query results for model [Botble\ACL\Models\User].

**Comment by sangnguyenplus** [comment]
Hi zhsolutions,
I checked on demo site and it's still working. I will check and update it if it has error.

Thanks for your feedback.

**Comment by zhsolutions** [comment]
Just did a fresh install from the repository, and the issue is in there, I tried to track it but, everything looks fine.. Hope you can see  it

**Comment by sangnguyenplus** [comment]
I'm fixing other bugs, so the next update will be released in a few days.
Thanks!
