### ISSUE TITLE
Including Slider

### ISSUE THREAD

**Issue by nikhil167** [botble/issues#14]
I am creating a new theme, and i want a main image slider in it.
how would i setup one.
Help I am a beginer.
Thanks

**Comment by sangnguyenplus** [comment]
Hi @nikhil167,
You can create your plugin and display it on your theme. Using command `php artisan plugin:create <plugin name>` to create your plugin.

Thanks!

**Comment by nikhil167** [comment]
Thanks Mate,
Another Problem my static blocks section is empty and i can't find the newly created items as well.
it shows 'no data to display'.
How it works?

**Comment by sangnguyenplus** [comment]
It's still here. Please see screenshot!
![screenshot](https://user-images.githubusercontent.com/6972407/27540167-63c2c5a4-5aa9-11e7-8abf-bfdd3430c246.png)

**Comment by nikhil167** [comment]
Nope that's not i meant. After creating a block i can't find it anywhere 
Here you created a 'sample block' and it shows in the below list as No.1, But Nothing is showing in Mine.
Sorry For the Confusion.

i'm attaching a screenshot
![botble](https://user-images.githubusercontent.com/26650913/27587104-a185e1de-5b60-11e7-9069-3d379919628f.jpg)

And it shows the success message as well after saving
![botble2](https://user-images.githubusercontent.com/26650913/27587218-1defa656-5b61-11e7-91cb-0bffb25f4872.jpg)

What i did wrong? Help.

**Comment by sangnguyenplus** [comment]
Hi @nikhil167,
Do you use the latest version on Codecanyon?
Please add my skype live:minhsang2603 then I will help you check your project.
Thanks!
