### ISSUE TITLE
uploading error

### ISSUE THREAD

**Issue by satellite111** [botble/issues#15]
![11](https://user-images.githubusercontent.com/29855714/27783467-f94a764a-5ff3-11e7-958b-7bb015419131.jpg)

**Comment by sangnguyenplus** [comment]
Hi @satellite111,
I fixed it and waiting Codecanyon approve the new update.
Thanks!

**Comment by satellite111** [comment]
oky

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by satellite111** [comment]
![1](https://user-images.githubusercontent.com/29855714/27825051-f8221222-60cb-11e7-88c0-4887023c5c39.jpg)



where is the routes, insert query ,form validation codes ?

**Comment by sangnguyenplus** [comment]
Hi @satellite111,

https://codecanyon.net/user/botble

Please send me a message using the form on the bottom right. 
![screenshot](https://user-images.githubusercontent.com/6972407/27825238-224c9074-60d9-11e7-95d6-cf4f869169c5.png)
I need to confirm that you're my customer.
Thanks!
