### ISSUE TITLE
data table warning

### ISSUE THREAD

**Issue by developr007** [botble/issues#16]
![1](https://user-images.githubusercontent.com/30045765/28017311-526f1ddc-6596-11e7-8734-3c9c75b53dc6.jpg)

**Comment by sangnguyenplus** [comment]
Hi @developr007,

https://codecanyon.net/user/botble

Please send me a message using the form on the bottom right. 
![screenshot](https://user-images.githubusercontent.com/6972407/27825238-224c9074-60d9-11e7-95d6-cf4f869169c5.png)
I need to confirm that you're my customer.
Thanks!

**Comment by sangnguyenplus** [comment]
Please help me change this line: `core/acl/src/Http/DataTables/UserDataTable.php:34`
to

```
return table_status(acl_is_user_activated($item) ? 1 : 0);
```

**Comment by sangnguyenplus** [comment]
It's fixed in current version.
Thanks!

**Comment by sunardo** [comment]
Still error in version 2.5
