### ISSUE TITLE
Dashboard Widgets

### ISSUE THREAD

**Issue by lukacavic** [botble/issues#17]
For example, I have Recent Posts widger, when I click close it is hidden from dashboard, but when I click "Manage Widgets" in modal it is show as active. After refreshing page, than is displayed as inactive.

The problem is after hiding widget from dashbard, widget is shown as active in Manage Widgets modal

![image](https://user-images.githubusercontent.com/4538071/28118180-665a73ca-6710-11e7-9cc9-48cd2b76e787.png)

**Comment by sangnguyenplus** [comment]
Hi @lukacavic,
I'm fixing it.
Thanks for you feedback!

**Comment by sangnguyenplus** [comment]
Hi @lukacavic,
I don't know why but it still works from my side and demo site http://cms.botble.com/admin is still working too.
Thanks!

**Comment by sangnguyenplus** [comment]
It's fixed in current version.
Thanks!
