### ISSUE TITLE
Settings, languages

### ISSUE THREAD

**Issue by lukacavic** [botble/issues#19]
I want to add another language, all fields are filled, but when I click on add language button, nothing is happening. Error is visible in console

![image](https://user-images.githubusercontent.com/4538071/28118485-7ae4d5b4-6711-11e7-82a2-aa23f02b790c.png)

**Comment by sangnguyenplus** [comment]
Hi @lukacavic,
I'm fixing it.
Thanks for you feedback!

**Comment by sangnguyenplus** [comment]
It's fixed in current version.
Thanks!
