### ISSUE TITLE
Edit language in Settings

### ISSUE THREAD

**Issue by lukacavic** [botble/issues#20]
When I try to edit language, nothing is happening

![image](https://user-images.githubusercontent.com/4538071/28118530-ad350cdc-6711-11e7-99cb-b99bb1cddad8.png)

**Comment by sangnguyenplus** [comment]
Hi @lukacavic,
I'm fixing it.
Thanks for you feedback!

**Comment by sangnguyenplus** [comment]
It's fixed in current version.
Thanks!

**Comment by RODOBTA** [comment]
I want to translate the entire project into Spanish, I created the folder is in resorces and I have translated every file from English to Spanish, I have changed the language in app.php, but somehow I am not translating it, I have to do something or something Am I doing wrong?

**Comment by sangnguyenplus** [comment]
Hi @RODOBTA,
You can run `php artisan vendor:publish --tag=lang` before translating it.

Thanks!

**Comment by RODOBTA** [comment]
I am new to Laravel, I already have all the files in their respective places and translated, now in my doubt is at what time I execute the command?

**Comment by sangnguyenplus** [comment]
Please send support request to my team using contact form in right sidebar here: https://codecanyon.net/user/botble

Thanks!
