### ISSUE TITLE
Custom fields field type not working

### ISSUE THREAD

**Issue by nikhil167** [botble/issues#21]
After creating the custom fields , field type like 'image' 'file' etc are not working while choosing images or files from the page section --->

![12](https://user-images.githubusercontent.com/26650913/28407347-73a802a8-6d51-11e7-8ec3-760a6d13ed03.jpg)
![11](https://user-images.githubusercontent.com/26650913/28407355-7c8dd9a6-6d51-11e7-84b0-8ea0472e9ba4.jpg)

**Comment by sangnguyenplus** [comment]
Hi @nikhil167,
I will check it.
Thanks!

**Comment by nikhil167** [comment]
Ok thanks, 
After creating Custom fields Now How i get the values on a page .
I am a front end developer help me with this code

<section class="main-slider" id="slider">

        <div class="tp-banner-container">
            <div class="tp-banner">
                <ul>
                 @foreach(get_field($page->id, BOTBLE_PAGES, 'slider', []) as $key => $slider)

                    <li data-transition="fade" data-slotamount="1" data-masterspeed="1000" data-thumb="{{ get_sub_field($slider, 'sliderpics') }}"  data-saveperformance="off"  data-title="Awesome Title Here">
                    <img src="{{ get_sub_field($slider, 'slider_image') }}"  alt=""  data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat">

                    <div class="tp-caption sfr sfb tp-resizeme"
                    data-x="left" data-hoffset="15"
                    data-y="center" data-voffset="-30"
                    data-speed="1500"
                    data-start="500"
                    data-easing="easeOutExpo"
                    data-splitin="none"
                    data-splitout="none"
                    data-elementdelay="0.01"
                    data-endelementdelay="0.3"
                    data-endspeed="1200"
                    data-endeasing="Power4.easeIn">
                    	<div class="content-box">
                        	<h2>{{ get_sub_field($slider, 'caption') }}</h2>
                            <div class="text"> {{ get_sub_field($slider, 'description') }}</div>
                            <div class="btn-box"><a href="#" class="theme-btn btn-style-one">{{ get_sub_field($slider, 'button') }}<span class="fa fa-long-arrow-right"></span></a></div>
                        </div>
                    </div>

                    </li>


                  
                    
                    @endforeach


                </ul>

            	<div class="tp-bannertimer"></div>
            </div>
        </div>
    </section>

Am i close :) Help.

**Comment by sangnguyenplus** [comment]
Your code looks good. It should work for you.

Thanks!

**Comment by nikhil167** [comment]
Nope its not working.  error screenshot-------->

![13](https://user-images.githubusercontent.com/26650913/28415086-dcce61ea-6d6b-11e7-884d-9ed59bbac1f6.jpg)

What about the custom field,field type error? Did u check that?
Thanks

**Comment by sangnguyenplus** [comment]
You should check this line because the error is "Undefined variable $object". I think "$object" should be "$page" or something that you got from your controller.
```
@foreach(get_field($object->id...
```

Thanks!

**Comment by nikhil167** [comment]
Thanks for the quick response,
Do you have any file to share or any demos related to this customfileds section.

Thanks.

**Comment by sangnguyenplus** [comment]
Actually, I don't use it for my projects. I just created it for other users.
I always use meta box to create a custom field, ref: http://docs.botble.com/cms/2.3/meta_box
Thanks!
