### ISSUE TITLE
Install Debugbar 

### ISSUE THREAD

**Issue by endytc** [botble/issues#23]
I have installed debugbar for previous version, 
https://github.com/barryvdh/laravel-debugbar/tree/2.4
I'm found error, I don't know this error from botble or debugbar.
but I try to install for other project, there is successfull. 

![image](https://user-images.githubusercontent.com/1209684/33920666-b590ff36-dff1-11e7-85db-6b48c3a73787.png)

**Comment by sangnguyenplus** [comment]
Hi, 
I think you need to setup mail credentials in .env file or change `ERROR_REPORTING_VIA_EMAIL=true` in .env to false.

Thanks!

**Comment by endytc** [comment]
Hi sangnguyenplus,
Oke thank's. Solved. 👍
