### ISSUE TITLE
Admin menu doesn't show in mobile

### ISSUE THREAD

**Issue by kaitoqueiroz** [botble/issues#24]
In a fresh install of botble CMS I see that the menu is never shown:

![image](https://user-images.githubusercontent.com/1447491/38555659-53451c14-3c9d-11e8-8692-37ab90870959.png)

**Comment by sangnguyenplus** [comment]
Hi,

We'll fix it as soon as possible.

Thank you for your feedback.

**Comment by sangnguyenplus** [comment]
For now, please use it on the desktop because it does not support mobile now. There're many UI need to do to use on mobile.

Thanks!

**Comment by sangnguyenplus** [comment]
We've fixed it, please use the latest version on Codecanyon.

Thanks!
