### ISSUE TITLE
Cannot access Plugin Page in Admin - Botble CMS

### ISSUE THREAD

**Issue by kaitoqueiroz** [botble/issues#25]
In a fresh install of botble CMS, this error shows when I try to access "/admin/plugins":

![image](https://user-images.githubusercontent.com/1447491/38565307-5a6eccd2-3cb7-11e8-9255-b28d36d455bc.png)

**Comment by sangnguyenplus** [comment]
Hi, 

Please remove /plugins/database folder.

Then it should work.

Thanks!

**Comment by sangnguyenplus** [comment]
Or you can use the latest version from Codecanyon, we've just updated it.

Thanks!
