### ISSUE TITLE
Composer install dependences + migrations, retrieve saved data doesn't works

### ISSUE THREAD

**Issue by kaitoqueiroz** [botble/issues#27]
I'm trying to install the CMS without use the database.sql and load the dependences with composer, just for deploy propose.

After run:
`php composer install`
`php artisan migrate`
`php artisan user:create`
`php artisan theme:activate ripple`
After this, I've activacted all plugins in /admin/plugins

Problem:

After insert in /admin Menu/Page/Category/Tag is not working the listing. I've checked database and it the saved data is there.

Just does not list anything.

![image](https://user-images.githubusercontent.com/1447491/38634646-89880456-3d99-11e8-91e3-51e5fc325037.png)

![image](https://user-images.githubusercontent.com/1447491/38634688-aa5386d8-3d99-11e8-8fc4-afdce6c76fc6.png)

**Comment by kaitoqueiroz** [comment]
Solved. I've imported languages in `/admin/system/translations` and set a default language, then when I save data its list works fine.

**Comment by sangnguyenplus** [comment]
Thank you :D
