### ISSUE TITLE
Impossible to create a new custom field in CMS

### ISSUE THREAD

**Issue by kaitoqueiroz** [botble/issues#28]
When I enter the page `/admin/custom-fields/create` shows a error.
![image](https://user-images.githubusercontent.com/1447491/38685349-1da65e40-3e48-11e8-9f4b-c53f2065edf7.png)

And I cannot add any "Field items information", clicking in "Add field", nothing happen.

**Comment by sangnguyenplus** [comment]
Hi, 

It's my mistake, please contact me via skype, I will send you the fixed files.

Thanks!
