### ISSUE TITLE
<Suggestion> Parent pages and posts date subpath permalinks

### ISSUE THREAD

**Issue by kaitoqueiroz** [botble/issues#29]
Suggestion just like Wordpress:
1) Permalinks in posts with date:
Ex.:
![image](https://user-images.githubusercontent.com/1447491/38739220-a50dced2-3f0a-11e8-81cd-3de12377260b.png)

2) Parent pages when create pages:
Ex.:
![image](https://user-images.githubusercontent.com/1447491/38739323-f6928086-3f0a-11e8-9a3d-b63c3375980a.png)
![image](https://user-images.githubusercontent.com/1447491/38739339-0435c6e4-3f0b-11e8-9122-72e583f589b0.png)

**Comment by sangnguyenplus** [comment]
Hi,

I think it's not a good idea because it's not good for SEO. You can read more about it here: https://moz.com/blog/15-seo-best-practices-for-structuring-urls

Thanks!
