### ISSUE TITLE
View folders in media by user id

### ISSUE THREAD

**Issue by refocusSystems** [botble/issues#30]
It doesnt seem to let you view only the folders created by a user in the media manager...I use S3. Anything I am missing?

**Comment by refocusSystems** [comment]
Not when you need per user files :)
On 6/1/2018 10:24:40 AM, Sang Nguyen <notifications@github.com> wrote:
Hi,
Sorry, we don't support that option. All media files are visible for all users. It's just like other CMS. It's easier to use.
Thanks!

**Comment by sangnguyenplus** [comment]
Sorry,

It's a big feature and it's just used for CRM system, not for normal websites.

Thanks!

**Comment by refocusSystems** [comment]
Hey, can you give me a quick sample how to login with the api?I cant seem to get it to authenticate using the clients api and the admin user creds
Thanx!

James
On 6/1/2018 10:38:19 AM, Sang Nguyen <notifications@github.com> wrote:
Sorry,
It's a big feature and it's just used for CRM system, not for normal websites.
Thanks!

**Comment by sangnguyenplus** [comment]
It still works for demo site. I'm using Postman to test it.
<img width="1247" alt="screen shot 2018-06-16 at 8 46 48 am" src="https://user-images.githubusercontent.com/6972407/41494730-eb0e594c-7141-11e8-864e-436742e5ea7f.png">
You can use default "Password grant token" or create new token. 
The document for it here: https://laravel.com/docs/5.6/passport#requesting-password-grant-tokens

Thanks!

**Comment by refocusSystems** [comment]
is the client id from users table? or is it the one generated in the api key creator?
On 6/15/2018 9:49:02 PM, Sang Nguyen <notifications@github.com> wrote:
It still works for demo site. I'm using Postman to test it.
[screen shot 2018-06-16 at 8 46 48 am] [https://user-images.githubusercontent.com/6972407/41494730-eb0e594c-7141-11e8-864e-436742e5ea7f.png]
You can use default "Password grant token" or create new token.
The document for it here: https://laravel.com/docs/5.6/passport#requesting-password-grant-tokens [https://laravel.com/docs/5.6/passport#requesting-password-grant-tokens]
Thanks!

**Comment by sangnguyenplus** [comment]
It's created from here: https://cms.botble.com/admin/api/clients

**Comment by refocusSystems** [comment]
Ok, got that.
I still get the main page as a response instead of json/token....
Can you look at your leisure?:
http://botble.hybridhostengine.com/
same login as demo

On 6/15/2018 9:59:51 PM, Sang Nguyen <notifications@github.com> wrote:
It's created from here: https://cms.botble.com/admin/api/clients [https://cms.botble.com/admin/api/clients]

**Comment by sangnguyenplus** [comment]
You have to set content-type is "application/json"
Please see
<img width="1230" alt="screenshot at jun 16 16-08-04" src="https://user-images.githubusercontent.com/6972407/41497445-900dc0da-717f-11e8-92e7-7c3e26bedb21.png">

**Comment by refocusSystems** [comment]
Thanks my friend! that worked...

Will that token allow api calls to any api routes I make?

great work on the whole thing...

I bought the payment, media and CMS system....
Thanks again for the help
cheers!

James
On 6/16/2018 5:09:03 AM, Sang Nguyen <notifications@github.com> wrote:
You have to set content-type is "application/json"
Please see
[screenshot at jun 16 16-08-04] [https://user-images.githubusercontent.com/6972407/41497445-900dc0da-717f-11e8-92e7-7c3e26bedb21.png]

**Comment by sangnguyenplus** [comment]
Sorry, I missed your question. 

Yes, this token can use in full system.

Thanks!

**Comment by refocusSystems** [comment]
How can I store json from inputs in form of plugin?
On 6/19/2018 6:43:55 AM, Sang Nguyen <notifications@github.com> wrote:
Sorry, I missed your question.
Yes, this token can use in full system.
Thanks!

**Comment by sangnguyenplus** [comment]
Use can store `json_encode($request->input('abc'));`

The document for form builder: http://kristijanhusak.github.io/laravel-form-builder/

**Comment by refocusSystems** [comment]
and how to add gallery input to plugin from?
On 8/10/2018 8:44:44 AM, Sang Nguyen <notifications@github.com> wrote:
Use can store json_encode($request->input('abc'));
The document for form builder: http://kristijanhusak.github.io/laravel-form-builder/ [http://kristijanhusak.github.io/laravel-form-builder/]

**Comment by sangnguyenplus** [comment]
You can add to your plugin service provider. 

```
\Gallery::registerModule(<YOUR_PLUGIN>_MODULE_SCREEN_NAME]);
```

The document: https://docs.botble.com/cms/3.2/plugin-gallery#how-to-add-gallery-to-your-plugin

**Comment by refocusSystems** [comment]
Sweet,, missed that...Thank You my friend!
On 8/10/2018 8:47:10 AM, Sang Nguyen <notifications@github.com> wrote:
You can add to your plugin service provider.
\Gallery::registerModule(<YOUR_PLUGIN>_MODULE_SCREEN_NAME]);
The document: https://docs.botble.com/cms/3.2/plugin-gallery#how-to-add-gallery-to-your-plugin [https://docs.botble.com/cms/3.2/plugin-gallery#how-to-add-gallery-to-your-plugin]

**Comment by refocusSystems** [comment]
One last thing 
how to get slug generated from name field...?

I didnt see in blog plugin where to do

On 8/10/2018 8:47:10 AM, Sang Nguyen <notifications@github.com> wrote:
You can add to your plugin service provider.
\Gallery::registerModule(<YOUR_PLUGIN>_MODULE_SCREEN_NAME]);
The document: https://docs.botble.com/cms/3.2/plugin-gallery#how-to-add-gallery-to-your-plugin [https://docs.botble.com/cms/3.2/plugin-gallery#how-to-add-gallery-to-your-plugin]

**Comment by sangnguyenplus** [comment]
Slug field just supports some forms now. So adding slug field to your forms will not work as your expectations. 

You can see in 

```
$this->app->booted(function () {
            config(['core.slug.general.supported' => array_merge(config('core.slug.general.supported'), [POST_MODULE_SCREEN_NAME])]);
});
```

Changing POST_MODULE_SCREEN_NAME by your module screen name.

You should build your slug field. It just needs to convert the name field to slug.

```
$slug = str_slug($request->input('name'));
```

**Comment by refocusSystems** [comment]
Can I grab the request 'name' on the the 'post create method' 
and use Sluggable on it there?
On 8/10/2018 9:26:16 AM, Sang Nguyen <notifications@github.com> wrote:
Slug field just supports some forms now. So adding slug field to your forms will not work as your expectations.
You can see in
$this->app->booted(function () { config(['core.slug.general.supported' => array_merge(config('core.slug.general.supported'), [POST_MODULE_SCREEN_NAME])]); });
Changing POST_MODULE_SCREEN_NAME by your module screen name.
You should build your slug field. It just needs to convert the name field to slug.
$slug = str_slug($request->input('name'));

**Comment by refocusSystems** [comment]
Hell again,
How can I move the 'Theme Options'  to under 'Dashboard' menu item?
On 8/10/2018 9:26:16 AM, Sang Nguyen <notifications@github.com> wrote:
Slug field just supports some forms now. So adding slug field to your forms will not work as your expectations.
You can see in
$this->app->booted(function () { config(['core.slug.general.supported' => array_merge(config('core.slug.general.supported'), [POST_MODULE_SCREEN_NAME])]); });
Changing POST_MODULE_SCREEN_NAME by your module screen name.
You should build your slug field. It just needs to convert the name field to slug.
$slug = str_slug($request->input('name'));

**Comment by sangnguyenplus** [comment]
You can use

```
dashboard_menu()
                ->removeItem('cms-core-theme-option')
                ->registerItem([
                    'id' => 'cms-core-theme-option',
                    'priority' => 4,
                    'parent_id' => 'cms-core-appearance',
                    'name' => trans('core.theme::theme.theme_options'),
                    'icon' => null,
                    'url' => route('theme.options'),
                    'permissions' => ['theme.options'],
                ]);
```

You can change `priority` or `parent_id` to move it.

**Comment by refocusSystems** [comment]
Thank you again
On 8/10/2018 8:14:50 PM, Sang Nguyen <notifications@github.com> wrote:
You can use
dashboard_menu() ->removeItem('cms-core-theme-option') ->registerItem([ 'id' => 'cms-core-theme-option', 'priority' => 4, 'parent_id' => 'cms-core-appearance', 'name' => trans('core.theme::theme.theme_options'), 'icon' => null, 'url' => route('theme.options'), 'permissions' => ['theme.options'], ]);
You can change priority or parent_id to move it.
