### ISSUE TITLE
CMS <Suggestion> Do not keep themes inside public folder

### ISSUE THREAD

**Issue by kaitoqueiroz** [botble/issues#31]
Maybe it's not a good idea to keep themes folder inside public folder.
.php files can be accessed directly from browser, I know that Apache/Nginx can be configured to not open this files, but maybe a good idea to keep this in another place.

**Comment by sangnguyenplus** [comment]
Currently, we're using this package to manage theme: https://github.com/teepluss/laravel-theme

Put themes in public folder to make it easy to use, easy to develop.

Thanks!
