### ISSUE TITLE
Error with variable $locales

### ISSUE THREAD

**Issue by drullandev** [botble/issues#36]
Hello!. Nice work, but i don't know why i found this problem just accessing to http://127.0.0.1:8000/admin
Undefined variable: locales (View: C:\www\git\botble-cms\core\base\resources\views\layouts\partials\top-header.blade.php) (View: C:\www\git\botble-cms\core\base\resources\views\layouts\partials\top-header.blade.php) (View: C:\www\git\botble-cms\core\base\resources\views\layouts\partials\top-header.blade.php)

**Comment by drullandev** [comment]
Some suggestion please? I'm stopped on these point waiting your response for our next steps! ;) How can avoid this error or find a solution ? Thanks!

**Comment by sangnguyenplus** [comment]
@drullandev Please leave a comment on Codecanyon, our support team will help you!

Thanks!

**Comment by drullandev** [comment]
Thanks a lot @sangnguyenplus ;)
