### ISSUE TITLE
与LaraMag 的区别在哪里？或者该选择购买哪一个？

### ISSUE THREAD

**Issue by jerecao** [botble/issues#38]
您的Botble与LaraMag都很棒，但是在envatomarket市场上，2者的介绍基本完全一样。唯一不同的可能是Botble的创建时间比LaraMag早一些，可否详细介绍一下两者的区别或者使用范围有什么差异的地方呢？或者说您对2者今后的维护和升级更偏向于哪个？
------------------------------------------------------------------------
Both your Botble and LaraMag are great, but in the envatomarket market, they are basically the same. The only difference may be that Botble was created earlier than LaraMag. Could you elaborate on the differences between the two or the scope of their use? Or which do you prefer for future maintenance and upgrade?

**Comment by jerecao** [comment]
为啥没有回答啊

**Comment by sangnguyenplus** [comment]
Hi, sorry but I don't speak Chinese.

You can check Botble & LaraMag, it has some different plugins. Botble has custom fields and LaraMag has facebook, simple slider plugins.

And it has different themes. Botble is our CMS and LaraMag is a product which using Botble CMS :D 

Thanks!
