### ISSUE TITLE
ErrorException in Locale.php line 29:

### ISSUE THREAD

**Issue by twhiting9275** [botble/issues#4]
Anywhere in the backend. Something is wrong here.

ErrorException in Locale.php line 29:
array_key_exists(): The first argument should be either a string or an integer

This was resolved by simply changing 
`      //          $locale = UserMeta::getMeta('admin-locale', false);`
to
`                        $locale = "admin";`

You need to fix this though if you're going to allow people to change the admin directory

**Comment by sangnguyenplus** [comment]
Hi @twhiting9275,
If you got error, you can change
`$locale = UserMeta::getMeta('admin-locale', false);` 
to 
`$locale = UserMeta::getMeta('admin-locale', config('app.locale'));`
Thanks!

**Comment by twhiting9275** [comment]
That solved that one, yes. Should be noted that one has to actually refresh the page once that's done
