### ISSUE TITLE
why are not find php artisan cms:create ?

### ISSUE THREAD

**Issue by jaccborn** [botble/issues#7]
i'm only see the php artisan cms:install  and cms:rebuild_permissions .

**Comment by sangnguyenplus** [comment]
Yes, 
You can not create other cms from current cms, if you need to do that, you have to copy all source code to other place and run cms:install to install new project.
Thanks!

**Comment by jaccborn** [comment]
yeah,i'm install cms success, but i need to create a moudle like demo in youtube video,what i can do? the struct as same as core/

**Comment by sangnguyenplus** [comment]
You can you command "php artisan plugin:create". The new plugin will be created in /plugins directory.
Other commands:
- plugin:activate
- plugin:deactivate
- plugin:remove

You can see all available command by run "php artisan --help"
Thanks!

**Comment by jaccborn** [comment]
ok, i know the cms:create the same as plugin:create,
very thank u, wish u have a good day bro.
