### ISSUE TITLE
Activating Users in Admin Area

### ISSUE THREAD

**Issue by zhsolutions** [botble/issues#8]
When trying to activate a user from the administration area, a success message is displayed, but when I reload the page, the users is back to deactivated.

**Comment by sangnguyenplus** [comment]
Hi @zhsolutions, 
I got it and I'm fixing it now.
Thanks!

**Comment by sangnguyenplus** [comment]
Hi @zhsolutions,

To fix this bug, please replace `$user->activated = $request->input('status');` on the line 209 in `core/acl/src/Http/Controllers/UserController.php` by below code:

```
if ($request->input('status', 0)) {
                $activation = Activation::create($user);

                if (Activation::complete($user, $activation->code)) {
                    do_action(BASE_ACTION_AFTER_UPDATE_CONTENT, USER_MODULE_SCREEN_NAME, $request, $user);
                }
            } else {
                Activation::remove($user);
            }
```

This bug will be fixed in the next update.

Thanks for your feedback!

**Comment by zhsolutions** [comment]
Excellent, thanks, Great work.

**Comment by sangnguyenplus** [comment]
Please let me know if you find any bugs.

Thanks!

**Comment by zhsolutions** [comment]
Mentioned Code was on Line ~149

Upon updating the file and clearing auto-load, issue exists still

**Comment by Denzla** [comment]
Not working for me, getting Internal Server Error?

**Comment by sangnguyenplus** [comment]
Hi @Denzla ,
What's Botble version that you're working on?
I think it should be fixed. I will update Botble on the Codecanyon soon.
Thanks!

**Comment by Denzla** [comment]
Hello. Downloaded from Codecanyon few days ago. That would be great, thanks.

**Comment by sangnguyenplus** [comment]
Please add my skype live:minhsang2603 then I can help you via Teamviewer if you got a bug.

Thanks!
