### ISSUE TITLE
Creating new Role

### ISSUE THREAD

**Issue by zhsolutions** [botble/issues#9]
When Creating a new role, the description field fails:

`SQLSTATE[HY000]: General error: 1364 Field 'description' doesn't have a default value (SQL: insert into `roles` (`name`, `slug`, `updated_at`, `created_at`) values (test, test, 2017-05-13 01:55:06, 2017-05-13 01:55:06))`

**Comment by sangnguyenplus** [comment]
Yes,
I fixed it. 

To fix this bug you can add this code to `core/acl/src/Models/Role.php:25`

```
protected $fillable = ['name', 'slug', 'description', 'is_staff', 'is_default', 'created_by', 'updated_by'];

```

This bug will be fixed in the next update.

Thanks!

**Comment by zhsolutions** [comment]
Confirmed fixed. Great stuff

**Comment by sangnguyenplus** [comment]
Please let me know if you find any bugs.
Thanks!
